### PR TITLE
Branches

### PR DESCRIPTION
**Pull request by Tarkan-Zarrouk**
idk how github works forgive me if I did some hickery dickery bullshit 
I read the code and it's actually nice lol

### CODE REVIEW

**Comment by Tarkan-Zarrouk** [comment]
idek if I did it correctly just check everything lol

**Comment by Tarkan-Zarrouk** [comment]
ok update, I think i fucked it up hold on

**Comment by therealbush** [comment]
huh whuh

**Comment by therealbush** [comment]
yeah the code could be better, I fixed it up on the paper version because I had to update the mappings for 1.18.2 anyways, but I really can't find a better way than basic reflection. I'm not sure it's worth the effort to try using access wideners or mixins on paper

**Pull request closed without merging**
